language: python

cache: pip

matrix:
  fast_finish: true
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
    - python: "3.8-dev"
      dist: xenial
    - python: "2.7"
      arch: ppc64le 
    - python: "3.4"
      arch: ppc64le
    - python: "3.5"
      arch: ppc64le
    - python: "3.6"
      arch: ppc64le
    - python: "3.7"
      dist: xenial
      arch: ppc64le
    - python: "3.8-dev"
      dist: xenial
      arch: ppc64le
    - python: "3.8"
      dist: xenial
      arch: ppc64le
  allow_failures:
    - python: "3.8-dev"

install:
    - pip install -e .

script:
    - pytest -xvv test.py
